version: '3.8'

services:
  db:
    container_name: postgres
    build:
      context: ./db
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d exampledb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  langchain:
    container_name: langchain
    build:
      context: ./langchain
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:XXXXXX@postgres/exampledb"
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    command: python app.py
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
